### ISSUE TITLE
what does self.b1 refer to

### ISSUE THREAD

**Issue by jpainam** [ukaukaaaa/GazeGNN#1]
Hi, thank you for sharing,

Do you mind telling what self.b1 refers to in this part of the code?

Thanks 
https://github.com/ukaukaaaa/GazeGNN/blob/48823a814cd7f6a21330744b60c0efbd5e33df55/models/pvig_gaze.py#L159

**Comment by ukaukaaaa** [comment]
> Hi, thank you for sharing,
> 
> Do you mind telling what self.b1 refers to in this part of the code?
> 
> Thanks
> 
> https://github.com/ukaukaaaa/GazeGNN/blob/48823a814cd7f6a21330744b60c0efbd5e33df55/models/pvig_gaze.py#L159

Hi, thanks for the comment.

self.b1 refers to one batch normalization layer coming from 
https://github.com/ukaukaaaa/GazeGNN/blob/48823a814cd7f6a21330744b60c0efbd5e33df55/models/pvig_gaze.py#L204

**Comment by jpainam** [comment]
Thank you, was looking for `self.b1 = ...`
