### ISSUE TITLE
Concern about the use of transforms.RandomResizedCrop(224) in data_transforms

### ISSUE THREAD

**Issue by ycczh2000** [ukaukaaaa/GazeGNN#3]
In the data_transforms section of read_data.py, you are using transforms.RandomResizedCrop(224), which is much smaller than the original image resolution. Doesn't this lead to most of the original image being cropped out?

**Comment by phy710** [comment]
This API resizes the image before crops it out.
https://pytorch.org/vision/stable/generated/torchvision.transforms.RandomResizedCrop.html
